addSbtPlugin("org.jetbrains.scala" % "sbt-ide-settings" % "1.1.2")
addSbtPlugin("org.portable-scala" % "sbt-scalajs-crossproject"      % "1.3.1")
//addSbtPlugin("org.portable-scala" % "sbt-scala-native-crossproject" % "1.3.1")
addSbtPlugin("org.scala-js"       % "sbt-scalajs"                   % "1.15.0")
//addSbtPlugin("org.scala-native"   % "sbt-scala-native"              % "0.4.16")
